"""
C1 calibration and threshold analysis pipeline.

Regenerates:
- docs/c1_threshold_sweep_report.md
- docs/c1_calibration_report.md
- docs/c1_operating_points.json

from a measured evaluation artifact (default: docs/c1_eval_base.json).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _safe_div(n: float, d: float) -> float:
    return n / d if d else 0.0


def _f1(p: float, r: float) -> float:
    return _safe_div(2 * p * r, p + r)


def _evaluate_threshold(rows: list[dict], thr: float) -> dict:
    tp = tn = fp = fn = 0
    for r in rows:
        y = 1 if r["truth"] == "FAKE" else 0
        p = float(r["fake_probability"])
        pred = 1 if p >= thr else 0

        if y == 1 and pred == 1:
            tp += 1
        elif y == 0 and pred == 0:
            tn += 1
        elif y == 0 and pred == 1:
            fp += 1
        else:
            fn += 1

    total = tp + tn + fp + fn
    precision_fake = _safe_div(tp, tp + fp)
    recall_fake = _safe_div(tp, tp + fn)
    f1_fake = _f1(precision_fake, recall_fake)
    precision_real = _safe_div(tn, tn + fn)
    recall_real = _safe_div(tn, tn + fp)
    f1_real = _f1(precision_real, recall_real)

    return {
        "threshold": thr,
        "accuracy": _safe_div(tp + tn, total),
        "precision_fake": precision_fake,
        "recall_fake": recall_fake,
        "f1_fake": f1_fake,
        "precision_real": precision_real,
        "recall_real": recall_real,
        "f1_real": f1_real,
        "f1_macro": (f1_fake + f1_real) / 2,
        "confusion_matrix": {
            "tp_fake_as_fake": tp,
            "tn_real_as_real": tn,
            "fp_real_as_fake": fp,
            "fn_fake_as_real": fn,
        },
    }


def _calibration_stats(rows: list[dict], bins: int = 10) -> dict:
    probs = [float(r["fake_probability"]) for r in rows]
    ys = [1 if r["truth"] == "FAKE" else 0 for r in rows]
    n = len(rows)

    brier = sum((p - y) ** 2 for p, y in zip(probs, ys)) / n

    ece = 0.0
    rel_bins = []
    for i in range(bins):
        lo = i / bins
        hi = (i + 1) / bins
        if i == bins - 1:
            idxs = [j for j, p in enumerate(probs) if lo <= p <= hi]
        else:
            idxs = [j for j, p in enumerate(probs) if lo <= p < hi]

        if not idxs:
            rel_bins.append(
                {
                    "bin": f"[{lo:.1f},{hi:.1f}{']' if i == bins - 1 else ')'}",
                    "count": 0,
                    "avg_prob": None,
                    "empirical_fake_rate": None,
                }
            )
            continue

        avg_p = sum(probs[j] for j in idxs) / len(idxs)
        emp = sum(ys[j] for j in idxs) / len(idxs)
        ece += (len(idxs) / n) * abs(avg_p - emp)

        rel_bins.append(
            {
                "bin": f"[{lo:.1f},{hi:.1f}{']' if i == bins - 1 else ')'}",
                "count": len(idxs),
                "avg_prob": avg_p,
                "empirical_fake_rate": emp,
            }
        )

    return {"brier_score": brier, "ece_10": ece, "reliability_bins": rel_bins}


def _fmt(x: float) -> str:
    return f"{x:.6f}"


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Run C1 threshold + calibration analysis from measured eval JSON.")
    p.add_argument(
        "--input",
        default="docs/c1_eval_base.json",
        help="Measured eval JSON generated by ai_deepfake/evaluate.py",
    )
    p.add_argument("--sweep-report", default="docs/c1_threshold_sweep_report.md")
    p.add_argument("--calibration-report", default="docs/c1_calibration_report.md")
    p.add_argument("--operating-points", default="docs/c1_operating_points.json")
    return p


def main() -> int:
    args = _build_parser().parse_args()

    in_path = Path(args.input).resolve()
    sweep_path = Path(args.sweep_report).resolve()
    calib_path = Path(args.calibration_report).resolve()
    ops_path = Path(args.operating_points).resolve()

    data = json.loads(in_path.read_text(encoding="utf-8"))
    rows = [r for r in data["per_image"] if r.get("status") == "ok"]
    if not rows:
        raise SystemExit("No status=ok rows available for C1 analysis.")

    thresholds = [round(i * 0.05, 2) for i in range(1, 20)]  # 0.05..0.95
    sweep = [_evaluate_threshold(rows, t) for t in thresholds]

    balanced = max(sweep, key=lambda x: (x["f1_macro"], x["accuracy"]))

    high_recall_candidates = [x for x in sweep if x["recall_fake"] >= 0.99]
    high_recall = (
        max(high_recall_candidates, key=lambda x: (x["f1_fake"], x["accuracy"]))
        if high_recall_candidates
        else max(sweep, key=lambda x: (x["recall_fake"], x["f1_fake"]))
    )

    high_precision_candidates = [x for x in sweep if x["precision_fake"] >= 0.98]
    high_precision = (
        max(high_precision_candidates, key=lambda x: (x["recall_fake"], x["f1_fake"]))
        if high_precision_candidates
        else max(sweep, key=lambda x: (x["precision_fake"], x["f1_fake"]))
    )

    calibration = _calibration_stats(rows, bins=10)

    operating_points = [
        {
            "intended_mode": "balanced",
            "threshold": balanced["threshold"],
            "is_default": True,
            "measured_metrics": {k: v for k, v in balanced.items() if k != "threshold"},
            "short_rationale": "Maximizes f1_macro across real/fake classes on frozen protocol.",
            "known_tradeoff": "Not optimized for extreme fake recall or extreme fake precision.",
        },
        {
            "intended_mode": "high_recall_fake_detection",
            "threshold": high_recall["threshold"],
            "is_default": False,
            "measured_metrics": {k: v for k, v in high_recall.items() if k != "threshold"},
            "short_rationale": "Prioritizes catching as many fake samples as possible (very high recall_fake).",
            "known_tradeoff": "More real images can be flagged fake (higher false positives).",
        },
        {
            "intended_mode": "high_precision_fake_detection",
            "threshold": high_precision["threshold"],
            "is_default": False,
            "measured_metrics": {k: v for k, v in high_precision.items() if k != "threshold"},
            "short_rationale": "Prioritizes confidence that flagged fake samples are truly fake (high precision_fake).",
            "known_tradeoff": "Misses more fake samples (lower recall_fake).",
        },
    ]

    ops_obj = {
        "phase": "C1",
        "protocol_anchor": "94.00% reproducible technical anchor from C0.5",
        "dataset_path": data["meta"]["data_dir"],
        "threshold_grid": thresholds,
        "default_operating_mode": "balanced",
        "default_threshold": balanced["threshold"],
        "operating_points": operating_points,
        "calibration_summary": {
            "brier_score": calibration["brier_score"],
            "ece_10": calibration["ece_10"],
        },
    }
    ops_path.write_text(json.dumps(ops_obj, ensure_ascii=False, indent=2), encoding="utf-8")

    sweep_lines = [
        "# C1 Threshold Sweep Report",
        "",
        "## Setup",
        "",
        f"- Dataset: `{data['meta']['data_dir']}`",
        f"- Counted samples (`status=ok`): `{len(rows)}`",
        "- Threshold grid: `0.05..0.95` step `0.05`",
        "",
        "## Threshold Policy Decision",
        "",
        f"- **Default operating point:** `balanced` at threshold `{balanced['threshold']}`",
        f"- High-recall fake-detection threshold: `{high_recall['threshold']}`",
        f"- High-precision fake-detection threshold: `{high_precision['threshold']}`",
        "- Decision source of truth: `docs/c1_operating_points.json`",
        "",
        "## Sweep Results",
        "",
        "| threshold | accuracy | precision_fake | recall_fake | f1_fake | precision_real | recall_real | f1_real | f1_macro | tp | tn | fp | fn |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]

    for r in sweep:
        cm = r["confusion_matrix"]
        sweep_lines.append(
            f"| {r['threshold']:.2f} | {_fmt(r['accuracy'])} | {_fmt(r['precision_fake'])} | {_fmt(r['recall_fake'])} | {_fmt(r['f1_fake'])} | "
            f"{_fmt(r['precision_real'])} | {_fmt(r['recall_real'])} | {_fmt(r['f1_real'])} | {_fmt(r['f1_macro'])} | "
            f"{cm['tp_fake_as_fake']} | {cm['tn_real_as_real']} | {cm['fp_real_as_fake']} | {cm['fn_fake_as_real']} |"
        )

    sweep_path.write_text("\n".join(sweep_lines) + "\n", encoding="utf-8")

    calib_lines = [
        "# C1 Calibration Report",
        "",
        "## Setup",
        "",
        f"- Dataset: `{data['meta']['data_dir']}`",
        f"- Samples (`status=ok`): `{len(rows)}`",
        "- Signal under analysis: `fake_probability`",
        "",
        "## Summary Metrics",
        "",
        f"- Brier score: `{calibration['brier_score']:.6f}`",
        f"- ECE (10 bins): `{calibration['ece_10']:.6f}`",
        "",
        "## Reliability Table (10 bins)",
        "",
        "| bin | count | avg_prob | empirical_fake_rate | abs_gap |",
        "| --- | --- | --- | --- | --- |",
    ]
    for b in calibration["reliability_bins"]:
        if b["count"] == 0:
            calib_lines.append(f"| {b['bin']} | 0 | - | - | - |")
        else:
            gap = abs(b["avg_prob"] - b["empirical_fake_rate"])
            calib_lines.append(
                f"| {b['bin']} | {b['count']} | {b['avg_prob']:.6f} | {b['empirical_fake_rate']:.6f} | {gap:.6f} |"
            )

    calib_lines += ["", "## Interpretation", ""]
    if calibration["ece_10"] <= 0.03:
        calib_lines.append("- Calibration appears strong on this dataset/protocol (low ECE).")
    elif calibration["ece_10"] <= 0.07:
        calib_lines.append("- Calibration appears moderate: usable, but threshold-dependent confidence caution is advised.")
    else:
        calib_lines.append("- Calibration appears weak: avoid interpreting fake_probability as calibrated confidence without further calibration.")
    calib_lines.append("- This report is purely measured from current detector scores; no calibration model was fitted in C1.")

    calib_path.write_text("\n".join(calib_lines) + "\n", encoding="utf-8")

    print("[OK] C1 analysis artifacts regenerated.")
    print(f"     default threshold: {balanced['threshold']}")
    print(f"     high recall threshold: {high_recall['threshold']}")
    print(f"     high precision threshold: {high_precision['threshold']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
