const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("Deploying ZK Deepfake Verification Contracts...\n");

    const [deployer] = await hre.ethers.getSigners();
    console.log("Deployer:", deployer.address);

    // 1. Deploy Groth16Verifier (generated by snarkjs)
    console.log("\n1. Deploying Groth16Verifier...");
    
    const Groth16Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
    const verifier = await Groth16Verifier.deploy();
    await verifier.waitForDeployment();
    
    const verifierAddress = await verifier.getAddress();
    console.log("   Groth16Verifier deployed to:", verifierAddress);

    // 2. Deploy ZKDeepfakeVerification
    console.log("\n2. Deploying ZKDeepfakeVerification...");
    
    const ZKDeepfakeVerification = await hre.ethers.getContractFactory("ZKDeepfakeVerification");
    const zkContract = await ZKDeepfakeVerification.deploy(verifierAddress);
    await zkContract.waitForDeployment();
    
    const zkContractAddress = await zkContract.getAddress();
    console.log("   ZKDeepfakeVerification deployed to:", zkContractAddress);

    // 3. Verify setup
    console.log("\n3. Verifying deployment...");
    const linkedVerifier = await zkContract.verifier();
    console.log("   Linked Verifier:", linkedVerifier);
    console.log("   Owner:", await zkContract.owner());

    // 4. Save deployment info
    const deploymentInfo = {
        network: hre.network.name,
        deployer: deployer.address,
        contracts: {
            Groth16Verifier: verifierAddress,
            ZKDeepfakeVerification: zkContractAddress
        },
        deployedAt: new Date().toISOString()
    };

    const deploymentPath = path.join(__dirname, "..", "deployment-zk.json");
    fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
    console.log("\n✅ Deployment info saved to deployment-zk.json");

    // 5. Update frontend .env
    const envPath = path.join(__dirname, "../../frontend/.env");
    let envContent = "";
    
    if (fs.existsSync(envPath)) {
        envContent = fs.readFileSync(envPath, "utf8");
    }

    // Add/update ZK contract address
    if (envContent.includes("VITE_ZK_CONTRACT_ADDRESS")) {
        envContent = envContent.replace(
            /VITE_ZK_CONTRACT_ADDRESS=.*/,
            `VITE_ZK_CONTRACT_ADDRESS=${zkContractAddress}`
        );
    } else {
        envContent += `\nVITE_ZK_CONTRACT_ADDRESS=${zkContractAddress}`;
    }

    if (envContent.includes("VITE_VERIFIER_ADDRESS")) {
        envContent = envContent.replace(
            /VITE_VERIFIER_ADDRESS=.*/,
            `VITE_VERIFIER_ADDRESS=${verifierAddress}`
        );
    } else {
        envContent += `\nVITE_VERIFIER_ADDRESS=${verifierAddress}`;
    }

    fs.writeFileSync(envPath, envContent.trim() + "\n");
    console.log("✅ Frontend .env updated");

    console.log("\n" + "=".repeat(50));
    console.log("DEPLOYMENT SUMMARY");
    console.log("=".repeat(50));
    console.log(`Groth16Verifier:        ${verifierAddress}`);
    console.log(`ZKDeepfakeVerification: ${zkContractAddress}`);
    console.log("=".repeat(50));
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
